# Generated by Django 4.2.6 on 2024-05-01 08:46

import chepareta.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChepareImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chepare_type', models.CharField(choices=[('safrid', 'safrid'), ('karagioz', 'karagioz'), ('chernokop', 'chernokop'), ('palamud', 'palamud')], max_length=20)),
                ('image', models.ImageField(upload_to=chepareta.utils.image_directory_distributor)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chepareta.seller')),
            ],
        ),
    ]
