# Generated by Django 4.2.6 on 2025-05-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField()),
                ('fish_spot', models.CharField()),
                ('fish_type', models.CharField()),
                ('quantity', models.FloatField()),
                ('lure_type', models.CharField()),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('snaps', models.PositiveIntegerField()),
                ('good_weather', models.BooleanField()),
            ],
        ),
    ]
