# Generated by Django 4.2.6 on 2023-10-16 21:51

from django.db import migrations, models
import fish_regions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurgasRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', fish_regions.models.CommonCharField(max_length=60)),
                ('sunrise', fish_regions.models.CommonCharField(max_length=60)),
                ('sunset', fish_regions.models.CommonCharField(max_length=60)),
                ('date', fish_regions.models.CommonCharField(max_length=60)),
                ('time', fish_regions.models.CommonCharField(max_length=60)),
                ('feels_like', models.IntegerField()),
                ('normal_temperature', models.IntegerField()),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
                ('weather_icon_url', fish_regions.models.CommonCharField(max_length=60)),
                ('wind_direction', fish_regions.models.CommonCharField(max_length=60)),
                ('wind_speed', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VarnaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', fish_regions.models.CommonCharField(max_length=60)),
                ('sunrise', fish_regions.models.CommonCharField(max_length=60)),
                ('sunset', fish_regions.models.CommonCharField(max_length=60)),
                ('date', fish_regions.models.CommonCharField(max_length=60)),
                ('time', fish_regions.models.CommonCharField(max_length=60)),
                ('feels_like', models.IntegerField()),
                ('normal_temperature', models.IntegerField()),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
                ('weather_icon_url', fish_regions.models.CommonCharField(max_length=60)),
                ('wind_direction', fish_regions.models.CommonCharField(max_length=60)),
                ('wind_speed', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
